/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.HMS;

import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Dileka
 */
public class PatientInformation extends javax.swing.JInternalFrame {
    UserAdmin useradmin;
    DefaultListModel listModel = new DefaultListModel();
    /**
     * Creates new form PatientInfomation
     */
    public PatientInformation() {
        initComponents();
        AddListPatientID();
    }
    //Add patient ids of patient to list from patient table 
     public void AddListPatientID(){
        try{
            Statement st=database.getStatement();
            ResultSet rs=st.executeQuery("SELECT PatientID FROM Patient");
            
            
            while (rs.next()) {
                String s=rs.getString("PatientID");
               
                listModel.addElement(s);
                
            }
            
            listPatient.setModel(listModel);
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        txtPid = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        radioMale = new javax.swing.JRadioButton();
        radioFemale = new javax.swing.JRadioButton();
        txtPhone = new javax.swing.JTextField();
        txtDisease = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        txtWno = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextPane();
        comboWard = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        listPatient = new javax.swing.JList<>();
        jLabel17 = new javax.swing.JLabel();
        dcDOB = new com.toedter.calendar.JDateChooser();
        dcCheckOut = new com.toedter.calendar.JDateChooser();
        dcCheckIn = new com.toedter.calendar.JDateChooser();

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Ward Details"));
        jScrollPane2.setHorizontalScrollBar(null);

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder("Personal Details"));
        jScrollPane3.setHorizontalScrollBar(null);

        setBackground(new java.awt.Color(244, 244, 254));
        setClosable(true);
        setIconifiable(true);
        setPreferredSize(new java.awt.Dimension(720, 510));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setText("Patient Infomation");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 300, -1));

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel3.setText("CheckIn Date");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 80, 20));

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel4.setText("Name with initials");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 110, 20));

        jLabel7.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel7.setText("Address");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 60, 30));

        jLabel8.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel8.setText("Phone Number");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, -1, -1));

        jLabel9.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel9.setText("Gender");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 90, 20));

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel1.setText("Patient ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel5.setText("Disease");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, -1));

        jLabel6.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel6.setText("Status of Disease");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 100, -1));

        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/HMS/Search-icon.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 100, -1));

        btnClose.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/HMS/symbol-delete-icon.png"))); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, -1, -1));

        jLabel10.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel10.setText("Ward Type");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 90, 20));

        jLabel13.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel13.setText("Ward No");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 70, 20));

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/HMS/update-icon.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 440, -1, -1));

        txtSearch.setEditable(false);
        txtSearch.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 90, 30));

        txtPid.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(txtPid, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 210, -1));

        txtName.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 210, -1));

        buttonGroup1.add(radioMale);
        radioMale.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        radioMale.setText("Male");
        getContentPane().add(radioMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, -1, -1));

        buttonGroup1.add(radioFemale);
        radioFemale.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        radioFemale.setText("Female");
        getContentPane().add(radioFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, -1, -1));

        txtPhone.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 210, -1));

        txtDisease.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtDisease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiseaseActionPerformed(evt);
            }
        });
        getContentPane().add(txtDisease, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 210, -1));

        txtStatus.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 210, -1));

        txtWno.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(txtWno, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 210, -1));

        txtAddress.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jScrollPane1.setViewportView(txtAddress);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 210, 40));

        comboWard.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        comboWard.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Ward", "Maternity", "Pediatrics", "Oncology", "Gynecologist", "Other" }));
        getContentPane().add(comboWard, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 210, -1));

        jLabel12.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel12.setText("CheckOut Date");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 90, 20));

        jLabel14.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel14.setText("Enter Patient ID");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 110, 30));

        listPatient.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        listPatient.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listPatientValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(listPatient);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 90, 290));

        jLabel17.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel17.setText("Date Of Birth");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 80, -1));

        dcDOB.setDateFormatString("dd,MM, yyyy");
        dcDOB.setName("dcDOB"); // NOI18N
        getContentPane().add(dcDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 210, -1));

        dcCheckOut.setDateFormatString("dd,MM, yyyy");
        dcCheckOut.setName("dcCheckOut"); // NOI18N
        getContentPane().add(dcCheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 210, -1));

        dcCheckIn.setDateFormatString("dd,MM, yyyy");
        dcCheckIn.setName("dcCheckIn"); // NOI18N
        getContentPane().add(dcCheckIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, 210, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
 
        //Search database which match the entered patient id
        try{
            
            Statement st=database.getStatement();
            ResultSet rs=st.executeQuery("SELECT * FROM Patient WHERE PatientID='"+txtSearch.getText()+"'");
            
            while(rs.next()){
                txtPid.setText(rs.getString("PatientID"));
                txtName.setText(rs.getString("NameWithInitials"));
                String GN = rs.getString("Gender");
                if (GN.equals("Female")){
                    radioMale.setSelected(false);
                    radioFemale.setSelected(true);

                }
                else{
                    radioFemale.setSelected(false);
                    radioMale.setSelected(true);
                } 
                txtAddress.setText(rs.getString("Address"));
                ((JTextField)dcDOB.getDateEditor().getUiComponent()).setText(rs.getString("DOB"));
                txtPhone.setText(rs.getString("PhoneNumber"));
                txtDisease.setText(rs.getString("Disease"));
                txtStatus.setText(rs.getString("StatusOfDisease"));
                txtWno.setText(rs.getString("WardNo"));
                comboWard.setSelectedItem(rs.getString("WardType"));                
                ((JTextField)dcCheckIn.getDateEditor().getUiComponent()).setText(rs.getString("CheckInDate"));
                ((JTextField)dcCheckOut.getDateEditor().getUiComponent()).setText(rs.getString("CheckOutDate"));
                }
            
        }
        catch(Exception ex){
            ex.printStackTrace();
        }
       
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        int x = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit?");
        if(x == 0){
            this.dispose();
        }
        
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        
        //Checking data fields of the jinternalform whether there are null values before update
        if(txtPid.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Patient Id can not be EMPTY!","Invalid Input!",JOptionPane.ERROR_MESSAGE);
        }
        else if(txtName.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Name With Initials can not be EMPTY!","Invalid Input!",JOptionPane.ERROR_MESSAGE);
        }
        else if(radioMale.isSelected()==false && radioFemale.isSelected()==false){
            JOptionPane.showMessageDialog(null,"Gender can not be NOT SELECTED!","Invalid Input!",JOptionPane.ERROR_MESSAGE);
        }
        else if(txtAddress.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Address can not be EMPTY!","Invalid Input!",JOptionPane.ERROR_MESSAGE);
        }
        else if(((JTextField)dcDOB.getDateEditor().getUiComponent()).getText().equals("")){
            JOptionPane.showMessageDialog(null,"Date Of Birth can not be EMPTY!","Invalid Input!",JOptionPane.ERROR_MESSAGE);
        }
        else if(txtPhone.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Phone Number can not be EMPTY!","Invalid Input!",JOptionPane.ERROR_MESSAGE);
        }
        else if(txtDisease.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Disease can not be EMPTY!","Invalid Input!",JOptionPane.ERROR_MESSAGE);
        }
        else if(txtStatus.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Status of disease can not be EMPTY!","Invalid Input!",JOptionPane.ERROR_MESSAGE);
        }
        else if(txtWno.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Ward number can not be EMPTY!","Invalid Input!",JOptionPane.ERROR_MESSAGE);
        }
        else if(comboWard.getSelectedItem().equals("Select Ward")){
            JOptionPane.showMessageDialog(null,"Ward type can not be NOT SELECTED!","Invalid Input!",JOptionPane.ERROR_MESSAGE);
        }
        else if(((JTextField)dcCheckIn.getDateEditor().getUiComponent()).getText().equals("")){
            JOptionPane.showMessageDialog(null,"CheckIn date can not be EMPTY!","Invalid Input!",JOptionPane.ERROR_MESSAGE);
        }
        else if(((JTextField)dcCheckOut.getDateEditor().getUiComponent()).getText().equals("")){
            JOptionPane.showMessageDialog(null,"CheckOut date can not be EMPTY!","Invalid Input!",JOptionPane.ERROR_MESSAGE);
        }
  
        else{
            
        
        int x = JOptionPane.showConfirmDialog(null, "Are you sure you want to update this record?");
        if(x == 0){
        
        try{ 
        String gender="";
            if(radioMale.isSelected()==true){
                gender="Male";
            }
            else{
                gender="Female";
            }
            String bday = ((JTextField)dcDOB.getDateEditor().getUiComponent()).getText();
            String date1 = ((JTextField)dcCheckIn.getDateEditor().getUiComponent()).getText();
            String date2 = ((JTextField)dcCheckOut.getDateEditor().getUiComponent()).getText();
            
            Statement st=database.getStatement();
            
            //Update tables with changed values
            st.executeUpdate("UPDATE Patient SET PatientID='"+txtPid.getText()+"', NameWithInitials='"+txtName.getText()+"', Gender='"+gender+"', Address='"+txtAddress.getText()+"', DOB='"+bday+"', PhoneNumber='"+txtPhone.getText()+"', Disease='"+txtDisease.getText()+"', StatusOfDisease='"+txtStatus.getText()+"', WardNo='"+txtWno.getText()+"', WardType='"+comboWard.getSelectedItem().toString()+"',CheckInDate='"+date1+"',CheckOutDate='"+date2+"' WHERE PatientID='"+txtPid.getText()+"'");
            
            st.executeUpdate("UPDATE Admission SET PatientID='"+txtPid.getText()+"', NameWithInitials='"+txtName.getText()+"', Gender='"+gender+"', Address='"+txtAddress.getText()+"', DOB='"+bday+"', PhoneNumber='"+txtPhone.getText()+"' WHERE PatientID='"+txtPid.getText()+"'");
            
            JOptionPane.showMessageDialog(null,"Data updated successfully!");
            
            //Empty the fields in jinternalform that entered 
            txtPid.setText("");
            txtName.setText("");
            buttonGroup1.clearSelection();
            txtAddress.setText("");
            ((JTextField)dcDOB.getDateEditor().getUiComponent()).setText("");
            txtPhone.setText("");
            txtDisease.setText("");
            txtStatus.setText("");
            txtWno.setText("");
            comboWard.setSelectedItem("Select Ward");
            ((JTextField)dcCheckIn.getDateEditor().getUiComponent()).setText("");
            ((JTextField)dcCheckOut.getDateEditor().getUiComponent()).setText("");
            
        }
        catch(Exception e){
            e.printStackTrace();
        }
        
        }
    }
    
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtDiseaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiseaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiseaseActionPerformed

    private void listPatientValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listPatientValueChanged
      
        //Set textfield to selected value 
        String selected = listPatient.getSelectedValue().toString();
       
        txtSearch.setText(selected);   
       
    }//GEN-LAST:event_listPatientValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboWard;
    private com.toedter.calendar.JDateChooser dcCheckIn;
    private com.toedter.calendar.JDateChooser dcCheckOut;
    private com.toedter.calendar.JDateChooser dcDOB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> listPatient;
    private javax.swing.JRadioButton radioFemale;
    private javax.swing.JRadioButton radioMale;
    private javax.swing.JTextPane txtAddress;
    private javax.swing.JTextField txtDisease;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPid;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtWno;
    // End of variables declaration//GEN-END:variables
}
