/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.HMS;

import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Dileka
 */
public class RegisteredPatients extends javax.swing.JInternalFrame {
    UserAdmin useradmin;
    DefaultListModel listModel = new DefaultListModel();
    /**
     * Creates new form RegisteredPatients
     */
    public RegisteredPatients() {
        initComponents();
        AddListPatientID();
    }

    //Add patient ids of patient to list from patient table
    public void AddListPatientID(){
        try{
            Statement st=database.getStatement();
            ResultSet rs=st.executeQuery("SELECT PatientID FROM Patient");
            
            
            while (rs.next()) {
                String s=rs.getString("PatientID");
                listModel.addElement(s);
            }
            
            listPatient.setModel(listModel);
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtPid = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        radioMale = new javax.swing.JRadioButton();
        radioFemale = new javax.swing.JRadioButton();
        txtPhone = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextPane();
        jLabel17 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        txtDisease = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPid1 = new javax.swing.JTextField();
        txtName1 = new javax.swing.JTextField();
        radioMale1 = new javax.swing.JRadioButton();
        radioFemale1 = new javax.swing.JRadioButton();
        txtPhone1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAddress1 = new javax.swing.JTextPane();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btnClose1 = new javax.swing.JButton();
        btnUpdate1 = new javax.swing.JButton();
        txtDisease1 = new javax.swing.JTextField();
        txtStatus1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        btnDelete1 = new javax.swing.JButton();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jPanel3 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtPid2 = new javax.swing.JTextField();
        txtName2 = new javax.swing.JTextField();
        radioMale2 = new javax.swing.JRadioButton();
        radioFemale2 = new javax.swing.JRadioButton();
        txtPhone2 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAddress2 = new javax.swing.JTextPane();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        btnClose2 = new javax.swing.JButton();
        btnUpdate2 = new javax.swing.JButton();
        txtDisease2 = new javax.swing.JTextField();
        txtStatus2 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        btnDelete2 = new javax.swing.JButton();
        jInternalFrame3 = new javax.swing.JInternalFrame();
        jPanel4 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        txtPid3 = new javax.swing.JTextField();
        txtName3 = new javax.swing.JTextField();
        radioMale3 = new javax.swing.JRadioButton();
        radioFemale3 = new javax.swing.JRadioButton();
        txtPhone3 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtAddress3 = new javax.swing.JTextPane();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        btnClose3 = new javax.swing.JButton();
        btnUpdate3 = new javax.swing.JButton();
        txtDisease3 = new javax.swing.JTextField();
        txtStatus3 = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        btnDelete3 = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        txtWno = new javax.swing.JTextField();
        comboWard = new javax.swing.JComboBox<>();
        jLabel51 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        listPatient = new javax.swing.JList<>();
        dcDOB = new com.toedter.calendar.JDateChooser();
        dcCheckIn = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(244, 244, 254));
        setClosable(true);
        setIconifiable(true);
        setPreferredSize(new java.awt.Dimension(720, 510));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 420));

        jLabel11.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setText("Registered Patients");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 310, -1));

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel4.setText("Name with initials");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 110, 20));

        jLabel7.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel7.setText("Address");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 60, 30));

        jLabel8.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel8.setText("Phone Number");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, -1, -1));

        jLabel9.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel9.setText("Gender");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 90, 20));

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel1.setText("Patient ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));

        txtPid.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(txtPid, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 210, -1));

        txtName.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 210, -1));

        buttonGroup1.add(radioMale);
        radioMale.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        radioMale.setText("Male");
        getContentPane().add(radioMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, -1, -1));

        buttonGroup1.add(radioFemale);
        radioFemale.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        radioFemale.setText("Female");
        getContentPane().add(radioFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, -1, -1));

        txtPhone.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 210, -1));

        txtAddress.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jScrollPane1.setViewportView(txtAddress);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 210, 40));

        jLabel17.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel17.setText("Date Of Birth");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 80, -1));

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel3.setText("CheckIn Date");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 80, 20));

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel5.setText("Disease");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, -1));

        jLabel6.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel6.setText("Status of Disease");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 100, -1));

        btnClose.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/HMS/symbol-delete-icon.png"))); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, -1, -1));

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/HMS/Add-icon.png"))); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 440, 100, -1));

        txtDisease.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtDisease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiseaseActionPerformed(evt);
            }
        });
        getContentPane().add(txtDisease, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 210, -1));

        txtStatus.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 210, -1));

        jInternalFrame1.setBackground(new java.awt.Color(255, 255, 255));
        jInternalFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jInternalFrame1.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 420));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Registered Patients");
        jInternalFrame1.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 230, -1));

        jLabel10.setText("Name with initials");
        jInternalFrame1.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 110, 20));

        jLabel14.setText("Address");
        jInternalFrame1.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 60, 30));

        jLabel16.setText("Phone Number");
        jInternalFrame1.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, -1));

        jLabel18.setText("Gender");
        jInternalFrame1.getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 90, 20));

        jLabel2.setText("Patient ID");
        jInternalFrame1.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));
        jInternalFrame1.getContentPane().add(txtPid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 210, -1));
        jInternalFrame1.getContentPane().add(txtName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 210, -1));

        radioMale1.setText("Male");
        jInternalFrame1.getContentPane().add(radioMale1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, -1, -1));

        radioFemale1.setText("Female");
        jInternalFrame1.getContentPane().add(radioFemale1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, -1, -1));
        jInternalFrame1.getContentPane().add(txtPhone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 210, -1));

        jScrollPane2.setViewportView(txtAddress1);

        jInternalFrame1.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 210, 40));

        jLabel19.setText("Date Of Birth");
        jInternalFrame1.getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 80, -1));

        jLabel20.setText("CheckIn Date");
        jInternalFrame1.getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 80, 20));

        jLabel21.setText("Disease");
        jInternalFrame1.getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, -1, -1));

        jLabel22.setText("Status of Disease");
        jInternalFrame1.getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 100, -1));

        btnClose1.setText("Close");
        btnClose1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClose1ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(btnClose1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, -1, -1));

        btnUpdate1.setText("Update");
        btnUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate1ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(btnUpdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, -1, -1));

        txtDisease1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDisease1ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(txtDisease1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 210, -1));
        jInternalFrame1.getContentPane().add(txtStatus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 210, -1));

        jLabel23.setText("CheckOut Date");
        jInternalFrame1.getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 90, 20));
        jInternalFrame1.getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 70, 30));

        btnDelete1.setText("Delete");
        btnDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete1ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(btnDelete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, -1, -1));

        jInternalFrame2.setBackground(new java.awt.Color(255, 255, 255));
        jInternalFrame2.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jInternalFrame2.getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 420));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel25.setText("Registered Patients");
        jInternalFrame2.getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 230, -1));

        jLabel26.setText("Name with initials");
        jInternalFrame2.getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 110, 20));

        jLabel27.setText("Address");
        jInternalFrame2.getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 60, 30));

        jLabel28.setText("Phone Number");
        jInternalFrame2.getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, -1));

        jLabel29.setText("Gender");
        jInternalFrame2.getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 90, 20));

        jLabel30.setText("Patient ID");
        jInternalFrame2.getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));
        jInternalFrame2.getContentPane().add(txtPid2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 210, -1));
        jInternalFrame2.getContentPane().add(txtName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 210, -1));

        radioMale2.setText("Male");
        jInternalFrame2.getContentPane().add(radioMale2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, -1, -1));

        radioFemale2.setText("Female");
        jInternalFrame2.getContentPane().add(radioFemale2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, -1, -1));
        jInternalFrame2.getContentPane().add(txtPhone2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 210, -1));

        jScrollPane3.setViewportView(txtAddress2);

        jInternalFrame2.getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 210, 40));

        jLabel31.setText("Date Of Birth");
        jInternalFrame2.getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 80, -1));

        jLabel32.setText("CheckIn Date");
        jInternalFrame2.getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 80, 20));

        jLabel33.setText("Disease");
        jInternalFrame2.getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, -1, -1));

        jLabel34.setText("Status of Disease");
        jInternalFrame2.getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 100, -1));

        btnClose2.setText("Close");
        btnClose2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClose2ActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(btnClose2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, -1, -1));

        btnUpdate2.setText("Update");
        btnUpdate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate2ActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(btnUpdate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, -1, -1));

        txtDisease2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDisease2ActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(txtDisease2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 210, -1));
        jInternalFrame2.getContentPane().add(txtStatus2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 210, -1));

        jLabel35.setText("CheckOut Date");
        jInternalFrame2.getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 90, 20));
        jInternalFrame2.getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 70, 30));

        btnDelete2.setText("Delete");
        btnDelete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete2ActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(btnDelete2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, -1, -1));

        jInternalFrame3.setBackground(new java.awt.Color(255, 255, 255));
        jInternalFrame3.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jInternalFrame3.getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 420));

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel37.setText("Registered Patients");
        jInternalFrame3.getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 230, -1));

        jLabel38.setText("Name with initials");
        jInternalFrame3.getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 110, 20));

        jLabel39.setText("Address");
        jInternalFrame3.getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 60, 30));

        jLabel40.setText("Phone Number");
        jInternalFrame3.getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, -1));

        jLabel41.setText("Gender");
        jInternalFrame3.getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 90, 20));

        jLabel42.setText("Patient ID");
        jInternalFrame3.getContentPane().add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));
        jInternalFrame3.getContentPane().add(txtPid3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 210, -1));
        jInternalFrame3.getContentPane().add(txtName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 210, -1));

        radioMale3.setText("Male");
        jInternalFrame3.getContentPane().add(radioMale3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, -1, -1));

        radioFemale3.setText("Female");
        jInternalFrame3.getContentPane().add(radioFemale3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, -1, -1));
        jInternalFrame3.getContentPane().add(txtPhone3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 210, -1));

        jScrollPane4.setViewportView(txtAddress3);

        jInternalFrame3.getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 210, 40));

        jLabel43.setText("Date Of Birth");
        jInternalFrame3.getContentPane().add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 80, -1));

        jLabel44.setText("CheckIn Date");
        jInternalFrame3.getContentPane().add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 80, 20));

        jLabel45.setText("Disease");
        jInternalFrame3.getContentPane().add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, -1, -1));

        jLabel46.setText("Status of Disease");
        jInternalFrame3.getContentPane().add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 100, -1));

        btnClose3.setText("Close");
        btnClose3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClose3ActionPerformed(evt);
            }
        });
        jInternalFrame3.getContentPane().add(btnClose3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, -1, -1));

        btnUpdate3.setText("Update");
        btnUpdate3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate3ActionPerformed(evt);
            }
        });
        jInternalFrame3.getContentPane().add(btnUpdate3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, -1, -1));

        txtDisease3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDisease3ActionPerformed(evt);
            }
        });
        jInternalFrame3.getContentPane().add(txtDisease3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 210, -1));
        jInternalFrame3.getContentPane().add(txtStatus3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 210, -1));

        jLabel47.setText("CheckOut Date");
        jInternalFrame3.getContentPane().add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 90, 20));
        jInternalFrame3.getContentPane().add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 70, 30));

        btnDelete3.setText("Delete");
        btnDelete3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete3ActionPerformed(evt);
            }
        });
        jInternalFrame3.getContentPane().add(btnDelete3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, -1, -1));

        jInternalFrame2.getContentPane().add(jInternalFrame3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jInternalFrame1.getContentPane().add(jInternalFrame2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jInternalFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/HMS/Search-icon.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 100, -1));

        jLabel49.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel49.setText("Ward Type");
        getContentPane().add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 70, 20));

        jLabel50.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel50.setText("Ward No");
        getContentPane().add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 90, 20));

        txtSearch.setEditable(false);
        txtSearch.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 90, 30));

        txtWno.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(txtWno, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 210, -1));

        comboWard.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        comboWard.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Ward", "Maternity", "Pediatrics", "Oncology", "Gynecologist", "Other" }));
        getContentPane().add(comboWard, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 210, 20));

        jLabel51.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel51.setText("Enter Patient ID");
        getContentPane().add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 110, 30));

        listPatient.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        listPatient.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listPatientValueChanged(evt);
            }
        });
        jScrollPane5.setViewportView(listPatient);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 90, 290));

        dcDOB.setDateFormatString("dd,MM, yyyy");
        dcDOB.setName("dcDOB"); // NOI18N
        getContentPane().add(dcDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 210, -1));

        dcCheckIn.setDateFormatString("dd,MM, yyyy");
        dcCheckIn.setName("dcCheckIn"); // NOI18N
        getContentPane().add(dcCheckIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, 210, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        int x = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit?");
        if(x == 0){
            this.dispose();
        }

    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        
        //Checking data fields of the jinternalform whether there are null values before insert
        if(txtPid.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Patient Id can not be EMPTY!","Invalid Input!",JOptionPane.ERROR_MESSAGE);
        }
        else if(txtName.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Name With Initials can not be EMPTY!","Invalid Input!",JOptionPane.ERROR_MESSAGE);
        }
        else if(radioMale.isSelected()==false && radioFemale.isSelected()==false){
            JOptionPane.showMessageDialog(null,"Gender can not be NOT SELECTED!","Invalid Input!",JOptionPane.ERROR_MESSAGE);
        }
        else if(txtAddress.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Address can not be EMPTY!","Invalid Input!",JOptionPane.ERROR_MESSAGE);
        }
        else if(((JTextField)dcDOB.getDateEditor().getUiComponent()).getText().equals("")){
            JOptionPane.showMessageDialog(null,"Date Of Birth can not be EMPTY!","Invalid Input!",JOptionPane.ERROR_MESSAGE);
        }
        else if(txtPhone.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Phone Number can not be EMPTY!","Invalid Input!",JOptionPane.ERROR_MESSAGE);
        }
        else if(txtDisease.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Disease can not be EMPTY!","Invalid Input!",JOptionPane.ERROR_MESSAGE);
        }
        else if(txtStatus.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Status of disease can not be EMPTY!","Invalid Input!",JOptionPane.ERROR_MESSAGE);
        }
        else if(txtWno.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Ward number can not be EMPTY!","Invalid Input!",JOptionPane.ERROR_MESSAGE);
        }
        else if(comboWard.getSelectedItem().equals("Select Ward")){
            JOptionPane.showMessageDialog(null,"Ward type can not be NOT SELECTED!","Invalid Input!",JOptionPane.ERROR_MESSAGE);
        }
        else if(((JTextField)dcCheckIn.getDateEditor().getUiComponent()).getText().equals("")){
            JOptionPane.showMessageDialog(null,"CheckIn date can not be EMPTY!","Invalid Input!",JOptionPane.ERROR_MESSAGE);
        }
        else{
        
        try{
          
            String gender=" ";
            if(radioMale.isSelected()==true){
                gender="Male";
            }
            else{
                gender="Female";
            }
            String bday = ((JTextField)dcDOB.getDateEditor().getUiComponent()).getText();
            String date1 = ((JTextField)dcCheckIn.getDateEditor().getUiComponent()).getText();
            String date2 = "Pending";
            
            Statement stat=database.getStatement();
            
            //Check whether there are duplicate patient ids
            ResultSet rs=stat.executeQuery("SELECT PatientID FROM Patient WHERE PatientID='"+txtPid.getText()+"'");
           
            if(rs.next()==true){
                JOptionPane.showMessageDialog(null,"Entered Patient ID already EXISTS!","Invalid Input!",JOptionPane.ERROR_MESSAGE);
            }
        
        
            else{
            
            //Insert data into patient table
            stat.executeUpdate("INSERT INTO Patient(PatientID,NameWithInitials,Gender,Address,DOB,PhoneNumber,Disease,StatusOfDisease,WardNo,WardType,CheckInDate,CheckOutDate) VALUES('"+txtPid.getText()+"','"+txtName.getText()+"','"+gender+"','"+txtAddress.getText()+"','"+bday+"','"+txtPhone.getText()+"','"+txtDisease.getText()+"','"+txtStatus.getText()+"','"+txtWno.getText()+"','"+comboWard.getSelectedItem().toString()+"','"+date1+"','"+date2+"')");
        
            JOptionPane.showMessageDialog(null,"Data added successfully!");
            
            //Empty the fields in jinternalform that entered 
            txtPid.setText("");
            txtName.setText("");
            buttonGroup1.clearSelection();
            txtAddress.setText("");
            ((JTextField)dcDOB.getDateEditor().getUiComponent()).setText("");
            txtPhone.setText("");
            txtDisease.setText("");
            txtStatus.setText("");
            txtWno.setText("");
            comboWard.setSelectedItem("Select Ward");
            ((JTextField)dcCheckIn.getDateEditor().getUiComponent()).setText("");
        
            
            }
        }
          
        catch(Exception e){
            e.printStackTrace();
        }
        
        
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtDiseaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiseaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiseaseActionPerformed

    private void btnClose1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClose1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClose1ActionPerformed

    private void btnUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdate1ActionPerformed

    private void txtDisease1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDisease1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDisease1ActionPerformed

    private void btnDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDelete1ActionPerformed

    private void btnClose2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClose2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClose2ActionPerformed

    private void btnUpdate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdate2ActionPerformed

    private void txtDisease2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDisease2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDisease2ActionPerformed

    private void btnDelete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDelete2ActionPerformed

    private void btnClose3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClose3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClose3ActionPerformed

    private void btnUpdate3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdate3ActionPerformed

    private void txtDisease3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDisease3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDisease3ActionPerformed

    private void btnDelete3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDelete3ActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed

        //Search database which match the entered patient id
        try{

            Statement st=database.getStatement();
            ResultSet rs=st.executeQuery("SELECT * FROM Patient WHERE PatientID='"+txtSearch.getText()+"'");

            while(rs.next()){
                txtPid.setText(rs.getString("PatientID"));
                txtName.setText(rs.getString("NameWithInitials"));
                String GN = rs.getString("Gender");
                if (GN.equals("Female")){
                    radioMale.setSelected(false);
                    radioFemale.setSelected(true);

                }
                else{
                    radioFemale.setSelected(false);
                    radioMale.setSelected(true);
                }
                txtAddress.setText(rs.getString("Address"));
                ((JTextField)dcDOB.getDateEditor().getUiComponent()).setText(rs.getString("DOB"));
                txtPhone.setText(rs.getString("PhoneNumber"));
                
            }

        }
        catch(Exception ex){
            ex.printStackTrace();
        }

    }//GEN-LAST:event_btnSearchActionPerformed

    private void listPatientValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listPatientValueChanged
        
        //Set textfield to selected value 
        String selected=listPatient.getSelectedValue().toString();
        txtSearch.setText(selected);
    }//GEN-LAST:event_listPatientValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnClose1;
    private javax.swing.JButton btnClose2;
    private javax.swing.JButton btnClose3;
    private javax.swing.JButton btnDelete1;
    private javax.swing.JButton btnDelete2;
    private javax.swing.JButton btnDelete3;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate1;
    private javax.swing.JButton btnUpdate2;
    private javax.swing.JButton btnUpdate3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboWard;
    private com.toedter.calendar.JDateChooser dcCheckIn;
    private com.toedter.calendar.JDateChooser dcDOB;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JInternalFrame jInternalFrame3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JList<String> listPatient;
    private javax.swing.JRadioButton radioFemale;
    private javax.swing.JRadioButton radioFemale1;
    private javax.swing.JRadioButton radioFemale2;
    private javax.swing.JRadioButton radioFemale3;
    private javax.swing.JRadioButton radioMale;
    private javax.swing.JRadioButton radioMale1;
    private javax.swing.JRadioButton radioMale2;
    private javax.swing.JRadioButton radioMale3;
    private javax.swing.JTextPane txtAddress;
    private javax.swing.JTextPane txtAddress1;
    private javax.swing.JTextPane txtAddress2;
    private javax.swing.JTextPane txtAddress3;
    private javax.swing.JTextField txtDisease;
    private javax.swing.JTextField txtDisease1;
    private javax.swing.JTextField txtDisease2;
    private javax.swing.JTextField txtDisease3;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtName1;
    private javax.swing.JTextField txtName2;
    private javax.swing.JTextField txtName3;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPhone1;
    private javax.swing.JTextField txtPhone2;
    private javax.swing.JTextField txtPhone3;
    private javax.swing.JTextField txtPid;
    private javax.swing.JTextField txtPid1;
    private javax.swing.JTextField txtPid2;
    private javax.swing.JTextField txtPid3;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtStatus1;
    private javax.swing.JTextField txtStatus2;
    private javax.swing.JTextField txtStatus3;
    private javax.swing.JTextField txtWno;
    // End of variables declaration//GEN-END:variables
}
