/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.HMS;
import java.awt.Image;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author Dileka
 */
public class UserAdmin extends javax.swing.JFrame {
    
    /**
     * Creates new form UserAdmin
     */
    public UserAdmin() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnPatientRegistration = new javax.swing.JButton();
        btnRegPatients = new javax.swing.JButton();
        btnEmployeeInfo = new javax.swing.JButton();
        btnWardInfo = new javax.swing.JButton();
        btnUserInformation = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnSalary = new javax.swing.JButton();
        btnTestsResults = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnPayment = new javax.swing.JButton();
        btnPatientInfo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ImageIcon icon=new ImageIcon(getClass().getResource("hms-admin.jpg"));
        Image image=icon.getImage();
        Window = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setName(""); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPatientRegistration.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnPatientRegistration.setText("Patient Registration");
        btnPatientRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientRegistrationActionPerformed(evt);
            }
        });
        jPanel2.add(btnPatientRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 160, -1));

        btnRegPatients.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRegPatients.setText("Registered Patients");
        btnRegPatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegPatientsActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegPatients, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 160, -1));

        btnEmployeeInfo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEmployeeInfo.setText("Employee Information");
        btnEmployeeInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeInfoActionPerformed(evt);
            }
        });
        jPanel2.add(btnEmployeeInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 160, -1));

        btnWardInfo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnWardInfo.setText("Ward Information");
        btnWardInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWardInfoActionPerformed(evt);
            }
        });
        jPanel2.add(btnWardInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 160, -1));

        btnUserInformation.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnUserInformation.setText("User Information");
        btnUserInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserInformationActionPerformed(evt);
            }
        });
        jPanel2.add(btnUserInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 160, -1));

        btnLogout.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/HMS/User-Interface-Logout-icon.png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 160, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Administrator");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 110, 30));

        btnSalary.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSalary.setText("Salary Of Employees");
        btnSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalaryActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 160, -1));

        btnTestsResults.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnTestsResults.setText("Tests & Results");
        btnTestsResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestsResultsActionPerformed(evt);
            }
        });
        jPanel2.add(btnTestsResults, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 160, -1));

        btnClose.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/HMS/symbol-delete-icon.png"))); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel2.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 160, -1));

        btnPayment.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnPayment.setText("Payment Details");
        btnPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentActionPerformed(evt);
            }
        });
        jPanel2.add(btnPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 160, -1));

        btnPatientInfo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnPatientInfo.setText("Patient Information");
        btnPatientInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientInfoActionPerformed(evt);
            }
        });
        jPanel2.add(btnPatientInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 160, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/HMS/Admin-icon.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 80, 70));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 580));

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("Hospial Management System");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 440, 50));

        Window.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout WindowLayout = new javax.swing.GroupLayout(Window);
        Window.setLayout(WindowLayout);
        WindowLayout.setHorizontalGroup(
            WindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        WindowLayout.setVerticalGroup(
            WindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        jPanel1.add(Window, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 720, 510));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/HMS/rsz_1ambulance-cross-hospital-icon-11.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 50, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnPatientRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientRegistrationActionPerformed
        
        //Load jInternal form in windowPane removing other forms
        Window.removeAll();
        PatientRegistration pr=new PatientRegistration();
        Window.add(pr).setVisible(true);
    }//GEN-LAST:event_btnPatientRegistrationActionPerformed

    private void btnRegPatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegPatientsActionPerformed
        Window.removeAll();
        RegisteredPatients rp=new RegisteredPatients();
        Window.add(rp).setVisible(true);
    }//GEN-LAST:event_btnRegPatientsActionPerformed

    private void btnEmployeeInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeInfoActionPerformed
        Window.removeAll();
        EmployeeInformation ei=new EmployeeInformation();
        Window.add(ei).setVisible(true);
    }//GEN-LAST:event_btnEmployeeInfoActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        int x = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit?");
        if(x == 0){
            this.dispose();
        }
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        
        //Navigate to homepage when logout button clicked
        HomeHMS homepage=new HomeHMS();
        homepage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentActionPerformed
        Window.removeAll();
        PaymentDetails pd=new PaymentDetails();
        Window.add(pd).setVisible(true);
    }//GEN-LAST:event_btnPaymentActionPerformed

    private void btnUserInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserInformationActionPerformed
        Window.removeAll();
        UserInformation ui=new UserInformation();
        Window.add(ui).setVisible(true);
    }//GEN-LAST:event_btnUserInformationActionPerformed

    private void btnTestsResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestsResultsActionPerformed
        Window.removeAll();
        TestsResults tr=new TestsResults();
        Window.add(tr).setVisible(true);
    }//GEN-LAST:event_btnTestsResultsActionPerformed

    private void btnWardInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWardInfoActionPerformed
        Window.removeAll();
        WardInformation wi=new WardInformation();
        Window.add(wi).setVisible(true);
    }//GEN-LAST:event_btnWardInfoActionPerformed

    private void btnPatientInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientInfoActionPerformed
        Window.removeAll();
        PatientInformation pi=new PatientInformation();
        Window.add(pi).setVisible(true);
    }//GEN-LAST:event_btnPatientInfoActionPerformed

    private void btnSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalaryActionPerformed
        Window.removeAll();
        EmployeeSalary es=new EmployeeSalary();
        Window.add(es).setVisible(true);
    }//GEN-LAST:event_btnSalaryActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserClinical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserClinical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserClinical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserClinical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Window;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnEmployeeInfo;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPatientInfo;
    private javax.swing.JButton btnPatientRegistration;
    private javax.swing.JButton btnPayment;
    private javax.swing.JButton btnRegPatients;
    private javax.swing.JButton btnSalary;
    private javax.swing.JButton btnTestsResults;
    private javax.swing.JButton btnUserInformation;
    private javax.swing.JButton btnWardInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
